############################################################
# Dockerfile to build Bowtie-Tophat2-cufflinks container images
# Based on centos:7
############################################################

# Set the base image to alpine
FROM centos:7

# File Author / Maintainer
MAINTAINER Dongye Li <dongye@gooalgene.com>,<dongye@gooalgene.com>

# runtime dependencies
RUN set -ex \
	&& yum install -y \
		perl \
		tar \
		unzip \
		wget \
	\
 	&& wget sourceforge.net/projects/bowtie-bio/files/bowtie2/2.2.9/bowtie2-2.2.9-linux-x86_64.zip \
	&& wget http://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.1.Linux_x86_64.tar.gz \
	&& wget http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.2.1.Linux_x86_64.tar.gz \
	&& mkdir -p /usr/src/bowtie2 \
	&& mkdir -p /usr/src/tophat \
	&& mkdir -p /usr/src/cufflinks \
	&& unzip bowtie2-2.2.9-linux-x86_64.zip \
	&& mv bowtie2-2.2.9/* /usr/src/bowtie2 \
	&& tar -zxC /usr/src/tophat --strip-components=1 -f tophat-2.1.1.Linux_x86_64.tar.gz \
	&& tar -zxC /usr/src/cufflinks --strip-components=1 -f cufflinks-2.2.1.Linux_x86_64.tar.gz \
	&& rm -rf bowtie2-2.2.9 bowtie2-2.2.9-linux-x86_64.zip tophat-2.1.1.Linux_x86_64.tar.gz cufflinks-2.2.1.Linux_x86_64.tar.gz \
	&& echo "export PATH=/usr/src/tophat:/usr/src/bowtie2:/usr/src/cufflinks:$PATH" >> /etc/profile \
	&& yum clean all

ENV PATH /usr/src/tophat:/usr/src/bowtie2:/usr/src/cufflinks:$PATH
